/** @typedef {{ exchange_short_name: string, timezone_label: string, market_open_local: string|null, market_close_local: string|null, announcement_source: string|null, manual_monitoring: boolean, fmp_symbol_format: string|null, yahoo_symbol_format: string|null, mapping_example: string|null, sort_order: number }} ExchangeSeedRow */

/** @type {ExchangeSeedRow[]} */

export const DEFAULT_EXCHANGE_ROWS = [
  {
    exchange_short_name: 'ASX',
    timezone_label: 'Australia/Sydney',
    market_open_local: '10:00',
    market_close_local: '16:00',
    announcement_source: 'ASX announcements',
    manual_monitoring: false,
    fmp_symbol_format: 'TICKER (no .AX)',
    yahoo_symbol_format: 'TICKER.AX',
    mapping_example: 'BHP → BHP.AX',
    sort_order: 10,
  },
  {
    exchange_short_name: 'LSE',
    timezone_label: 'Europe/London',
    market_open_local: '08:00',
    market_close_local: '16:30',
    announcement_source: 'LSE RNS',
    manual_monitoring: false,
    fmp_symbol_format: 'TICKER.L',
    yahoo_symbol_format: 'TICKER.L',
    mapping_example: 'DPLM.L → DPLM.L',
    sort_order: 20,
  },
  {
    exchange_short_name: 'NYSE',
    timezone_label: 'America/New_York',
    market_open_local: '09:30',
    market_close_local: '16:00',
    announcement_source: 'SEC EDGAR RSS',
    manual_monitoring: false,
    fmp_symbol_format: 'TICKER',
    yahoo_symbol_format: 'TICKER',
    mapping_example: 'AAPL → AAPL',
    sort_order: 30,
  },
  {
    exchange_short_name: 'NASDAQ',
    timezone_label: 'America/New_York',
    market_open_local: '09:30',
    market_close_local: '16:00',
    announcement_source: 'SEC EDGAR RSS',
    manual_monitoring: false,
    fmp_symbol_format: 'TICKER',
    yahoo_symbol_format: 'TICKER',
    mapping_example: 'MSFT → MSFT',
    sort_order: 40,
  },
  {
    exchange_short_name: 'TSX',
    timezone_label: 'America/Toronto',
    market_open_local: '09:30',
    market_close_local: '16:00',
    announcement_source: 'SEDAR — manual monitoring flag',
    manual_monitoring: true,
    fmp_symbol_format: 'TICKER.TO',
    yahoo_symbol_format: 'TICKER.TO',
    mapping_example: 'RY.TO → RY.TO',
    sort_order: 50,
  },
]
